vim.keymap.set("n", "<leader>,", ":nohlsearch<CR>")
vim.keymap.set("n", "gd", "<C-]>")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "<leader>l", ":vsplit<CR>")
vim.keymap.set("n", "<leader>gl", ":wincmd l<CR>")
vim.keymap.set("n", "<leader>gh", ":wincmd h<CR>")
